(()=>{const vp=document.querySelector('#mapViewport'),world=document.querySelector('#mapWorld'),W=1536,H=1024;let scale=1,x=0,y=0,minScale=.5,maxScale=3.2,drag=false,sx=0,sy=0,bx=0,by=0,pointers=new Map(),pinchDist=0,pinchScale=1;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function limits(){const vw=vp.clientWidth,vh=vp.clientHeight;minScale=Math.max(vw/W,vh/H)*.96;scale=clamp(scale,minScale,maxScale);const sw=W*scale,sh=H*scale;x=sw<=vw?(vw-sw)/2:clamp(x,vw-sw,0);y=sh<=vh?(vh-sh)/2:clamp(y,vh-sh,0)}
function draw(){limits();world.style.transform=`translate3d(${x}px,${y}px,0) scale(${scale})`}
function reset(){scale=Math.max(vp.clientWidth/W,vp.clientHeight/H)*1.04;x=(vp.clientWidth-W*scale)/2;y=(vp.clientHeight-H*scale)/2;draw()}
function zoomAt(f,cx=vp.clientWidth/2,cy=vp.clientHeight/2){const ns=clamp(scale*f,minScale,maxScale),wx=(cx-x)/scale,wy=(cy-y)/scale;x=cx-wx*ns;y=cy-wy*ns;scale=ns;draw()}
vp.addEventListener('wheel',e=>{e.preventDefault();const r=vp.getBoundingClientRect();zoomAt(Math.exp(-e.deltaY*.0015),e.clientX-r.left,e.clientY-r.top);hideHint()},{passive:false});
vp.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;vp.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===1){drag=true;sx=e.clientX;sy=e.clientY;bx=x;by=y;vp.classList.add('dragging')}else if(pointers.size===2){const a=[...pointers.values()];pinchDist=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);pinchScale=scale}hideHint()});
vp.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){const a=[...pointers.values()],d=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),r=vp.getBoundingClientRect(),cx=(a[0].x+a[1].x)/2-r.left,cy=(a[0].y+a[1].y)/2-r.top,ns=clamp(pinchScale*d/pinchDist,minScale,maxScale),wx=(cx-x)/scale,wy=(cy-y)/scale;x=cx-wx*ns;y=cy-wy*ns;scale=ns;draw()}else if(drag){x=bx+e.clientX-sx;y=by+e.clientY-sy;draw()}});
function up(e){pointers.delete(e.pointerId);if(pointers.size<2)pinchDist=0;if(!pointers.size){drag=false;vp.classList.remove('dragging')}else{const a=[...pointers.values()][0];sx=a.x;sy=a.y;bx=x;by=y}}
vp.addEventListener('pointerup',up);vp.addEventListener('pointercancel',up);
document.querySelector('#zoomIn').onclick=()=>zoomAt(1.28);document.querySelector('#zoomOut').onclick=()=>zoomAt(.78);document.querySelector('#resetMap').onclick=reset;window.addEventListener('resize',reset);
const card=document.querySelector('#cabinCard'),name=document.querySelector('#cabinName'),meta=document.querySelector('#cabinMeta');document.querySelectorAll('.cabin-pin').forEach(p=>p.addEventListener('click',e=>{e.stopPropagation();document.querySelectorAll('.cabin-pin').forEach(q=>q.classList.remove('active'));p.classList.add('active');name.textContent=p.dataset.name;meta.textContent=p.dataset.meta;card.classList.add('open');hideHint()}));document.querySelector('#closeCard').onclick=()=>{card.classList.remove('open');document.querySelectorAll('.cabin-pin').forEach(q=>q.classList.remove('active'))};
const hint=document.querySelector('#mapInstructions');function hideHint(){hint.classList.add('hidden')}document.querySelector('#mapHelp').onclick=()=>hint.classList.toggle('hidden');reset();})();
